version: '3.4'

services:
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
  Dito.Timeline:
    image: ditotimeline
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mongo