version: '2.1'

services:
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:latest
    ports:
        - "27017:27017"
    restart: always
  mongo_seed:
    build: ./mongo_seed
    volumes:
        - ./events/events.json:/usr/bin/events.json
    depends_on:
      - mongo
  dito.timelinenode:
    image: dito.timelinenode
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongo